services:
  - type: web
    name: examination-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: examination-db
          property: connectionString

databases:
  - name: examination-db
    plan: free
    ipAllowList: []